# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "none";
    neededForBoot = true;
    fsType = "tmpfs";
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/2e5f0b8a-9199-446c-a85a-f08e007b7fec";
    neededForBoot = true;
    fsType = "btrfs";
    options = ["defaults" "compress-force=zstd" "noatime" "ssd" "subvol=nix"];
  };

  boot.initrd.luks.devices."enc_nvme".device = "/dev/disk/by-uuid/88d3f469-9f65-473b-a0d9-07d4878806de";

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/2e5f0b8a-9199-446c-a85a-f08e007b7fec";
    neededForBoot = true;
    fsType = "btrfs";
    options = ["defaults" "compress-force=zstd" "noatime" "ssd" "subvol=persist"];
  };

  fileSystems."/home/jeosas/Games" = {
    device = "/dev/disk/by-uuid/6ee74d97-af29-4a51-977a-84d69ccbf1ab";
    neededForBoot = true;
    fsType = "btrfs";
    options = ["defaults" "compress-force=zstd" "noatime" "ssd" "subvol=games"];
  };

  boot.initrd.luks.devices."enc_ssd".device = "/dev/disk/by-uuid/cf407dba-946c-47f5-91ad-983822758135";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9C64-A54B";
    fsType = "vfat";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
