[
  # keep-sorted start case=no numeric=yes
  ./apps/alvr.nix
  ./apps/ankama-launcher.nix
  ./apps/azure.nix
  ./apps/bat.nix
  ./apps/blender.nix
  ./apps/btop.nix
  ./apps/direnv.nix
  ./apps/docker.nix
  ./apps/envision.nix
  ./apps/fastfetch.nix
  ./apps/firefox.nix
  ./apps/gcloud.nix
  ./apps/gh.nix
  ./apps/git.nix
  ./apps/godot.nix
  ./apps/heroic.nix
  ./apps/inkscape.nix
  ./apps/keyd.nix
  ./apps/kitty.nix
  ./apps/krita.nix
  ./apps/kubectl.nix
  ./apps/libreoffice.nix
  ./apps/mixxx.nix
  ./apps/mullvad-vpn.nix
  ./apps/mullvad.nix
  ./apps/neovim.nix
  ./apps/ollama.nix
  ./apps/ongaku.nix
  ./apps/openrazer.nix
  ./apps/oversteer.nix
  ./apps/qemu.nix
  ./apps/signal.nix
  ./apps/starship.nix
  ./apps/steam.nix
  ./apps/tldr.nix
  ./apps/transmission.nix
  ./apps/vagrant.nix
  ./apps/vesktop.nix
  ./apps/wireguard.nix
  ./apps/wivrn.nix
  ./apps/wootility.nix
  ./apps/xournal.nix
  ./apps/yazi.nix
  ./apps/zsh.nix
  ./services/nginx.nix
  # keep-sorted end
]
