[
  # keep-sorted start case=no numeric=yes
  ./apps/alvr.nix
  ./apps/ankama-launcher.nix
  ./apps/bash.nix
  ./apps/bat.nix
  ./apps/blender.nix
  ./apps/btop.nix
  ./apps/direnv.nix
  ./apps/discord.nix
  ./apps/docker.nix
  ./apps/envision.nix
  ./apps/eza.nix
  ./apps/fastfetch.nix
  ./apps/fd.nix
  ./apps/firefox.nix
  ./apps/ghostty.nix
  ./apps/git.nix
  ./apps/heroic.nix
  ./apps/inkscape.nix
  ./apps/jj.nix
  ./apps/keyd.nix
  ./apps/krita.nix
  ./apps/libreoffice.nix
  ./apps/mixxx.nix
  ./apps/mullvad.nix
  ./apps/neovim.nix
  ./apps/obs.nix
  ./apps/ollama.nix
  ./apps/ongaku.nix
  ./apps/openrazer.nix
  ./apps/oversteer.nix
  ./apps/signal.nix
  ./apps/starship.nix
  ./apps/libvirtd.nix
  ./apps/steam.nix
  ./apps/stow.nix
  ./apps/tldr.nix
  ./apps/transmission.nix
  ./apps/wireguard.nix
  ./apps/wivrn.nix
  ./apps/wootility.nix
  ./apps/xournal.nix
  ./apps/yazi.nix
  ./apps/zoxide.nix
  ./apps/zsh.nix
  ./services/goatcounter.nix
  ./services/nginx.nix
  ./services/unbound.nix
  # keep-sorted end
]
