#!/bin/bash

DISK=/dev/nvme0n1

# Setup partitions
# /boot

# / (btrfs)


# Setup LUKS encryption
cryptsetup --verify-passphrase -v luksFormat "$DISK"p3
cryptsetup open "$DISK"p3 enc

# Format
mkfs.vfat -n boot "$DISK"p1
mkfs.btrfs /dev/mapper/enc

# make subvolumes
mount -t btrfs /dev/mapper/enc  -o compress-force=zstd,noatime,ssd /mnt
btrfs subvolume create /mnt/nix
btrfs subvolume create /mnt/persist
umount /mnt

# Mounting everything
mount -t tmpfs none /mnt
mkdir /mnt/{boot,persist,nix}
mount -o subvol=root,compress=zstd,noatime,ssd /dev/mapper/enc /mnt
mount -o subvol=persist,compress=zstd,noatime,ssd /dev/mapper/enc /mnt/persist
mount "$DISK"p1 /mnt/boot

nixos-generate-config --root /mnt
