# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  config,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    neededForBoot = true;
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/58d1b70f-c8ee-4a91-9f43-26f34a73f38c";
    fsType = "btrfs";
    neededForBoot = true;
    options = ["defaults" "compress-force=zstd" "noatime" "ssd" "subvol=nix"];
  };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/60d24361-258d-4b4b-9736-346432d6f759";

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/58d1b70f-c8ee-4a91-9f43-26f34a73f38c";
    fsType = "btrfs";
    neededForBoot = true;
    options = ["defaults" "compress-force=zstd" "noatime" "ssd" "subvol=persist"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4BCA-28EA";
    fsType = "vfat";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
