# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "rfastpool/local/root";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "rfastpool/local/nix";
    fsType = "zfs";
  };

  fileSystems."/persist" = {
    device = "rfastpool/safe/persist";
    fsType = "zfs";
  };

  fileSystems."/var/log" = {
    device = "rfastpool/local/log";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "rfastpool/local/home";
    fsType = "zfs";
  };

  fileSystems."/data" = {
    device = "rcoldpool/safe/data";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/083D-FC66";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/boot-fallback" = {
    device = "/dev/disk/by-uuid/0D5A-3239";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/38e18008-e151-453c-9d93-611ae4e3fea0"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
