#!/bin/bash
zscroll -l 40 -b "󰝚  " \
        --delay 0.3 \
        --scroll-padding "      " \
        --match-command "bash $HOME/.config/eww/bar/scripts/music-current --status" \
        --match-text "Playing" "--scroll 1" \
        --match-text "Paused" "--scroll 0" \
        --update-check true "bash $HOME/.config/eww/bar/scripts/music-current"
