{...}: {
  imports = [
    ./firefox
    ./neovim
    ./alacritty.nix
    ./alvr.nix
    ./ankama-launcher.nix
    ./blender.nix
    ./discord.nix
    ./docker.nix
    ./freecad.nix
    ./godot.nix
    ./heroic.nix
    ./inkscape.nix
    ./kmonad.nix
    ./krita.nix
    ./libreoffice.nix
    ./lutris.nix
    ./mixxx.nix
    ./mullvad.nix
    ./ongaku.nix
    ./openrazer.nix
    ./oversteer.nix
    ./pdf.nix
    ./qemu.nix
    ./signal.nix
    ./steam.nix
    ./transmission.nix
    ./ungoogled-chromium.nix
    ./vesktop.nix
    ./wootility.nix
  ];
}
