#!/bin/bash

set -euo pipefail

DISK=/dev/nvme0n1

# Setup partitions
parted --script --align optimal "$DISK" -- \
  mktable gpt \
  \
  mkpart boot 0% 512MiB \
  type 1 C12A7328-F81F-11D2-BA4B-00A0C93EC93B \
  set 1 esp on \
  \
  mkpart root 512MiB 100% \
  type 2 CA7D7CCB-63ED-4C53-861C-1742536059CC \
  print

# Setup LUKS encryption
cryptsetup --verify-passphrase -v luksFormat "$DISK"p2
cryptsetup open "$DISK"p2 enc

# Format
mkfs.vfat -n boot "$DISK"p1
mkfs.btrfs /dev/mapper/enc

# make subvolumes
mount -t btrfs /dev/mapper/enc  -o compress-force=zstd,noatime,ssd /mnt
btrfs subvolume create /mnt/nix
btrfs subvolume create /mnt/persist
umount /mnt

# Mounting everything
mount -t tmpfs none /mnt
mkdir /mnt/{boot,persist,nix}
mount -o subvol=nix,compress=zstd,noatime,ssd /dev/mapper/enc /mnt/nix
mount -o subvol=persist,compress=zstd,noatime,ssd /dev/mapper/enc /mnt/persist
mount "$DISK"p1 /mnt/boot

nixos-generate-config --root /mnt
